README.md
fallenswordhelper.user.js

Update headers for GitHub

---

fallenswordhelper.user.js

Fix missing jQuery in Guide for Chrome

Fix missing jQuery in Guide for Chrome

---

fallenswordhelper.user.js

Layout fixes for guild chat and empty mailbox fix

Guild chat

---

fallenswordhelper.user.js

@gschizas & @yuuzhan
Show all quest steps in UFSG instead of Quest Book
Fix combat viewer since 20150511 UI update
Remove various bits of legacy code
Turn code to remove guild avatar border into function
New guild log messages (TODO Titans)
Updated internal references from Google to GitHub
Remove Titan Log
Remove Create Maps
Remove ShowGoldOnFindPlayer per HCS request
Remove UFSG widgets
Remove old guild log
Remove Check Items
Remove Inject Skills Page
Remove Old UI code
Remove Show AH Price in Inventory Manager
Comment out old AH functions

Small fixes

---

.jshintrc
fallenswordhelper.user.js

@fallenswordhelper/owners 
Sorry this is so big. As you can imagine there are many small changes and only a few major ones.
Performance is significantly improved though.

Linting part 1 and performance enhancements

---

fallenswordhelper.user.js

Small bug fixes

---

calfSystem.js
fallenswordhelper.user.js

Updated version number
Removed Dev logging from System

Restore FSBox functionality

---

.jshintrc
calfSystem.css
calfSystem.js
fallenswordhelper.user.js

More fairly major changes happening here.
New gold upgrades alert which I figured would be handy as people are always
forgetting. It works in a similar manner to the Temple check.
I've completed the move over to the new member list. This has several elements.
It means we are no longer scraping the guild page in the background which was a
very expensive operation. It is also using IndexedDB for storage which I'm
hoping will be a better way to store and retrieve all our data in future. I'm
also hoping that it will mean people don't lose their settings as often. There's
a long way to go here but the essential architecture is now in and available for
use.
I've started optimising the relic page. It's only a beginning right now but I
have some useful performance improvements already.
I've fixed …

FSH Update 1505 - Gold upgrades check, new member list etc.

---

fallenswordhelper.user.js

Fix regressions in creature combat analysis

Fix Send As Mass for enhanced text entry

---

calfSystem.js
fallenswordhelper.user.js

Chrome native, QuickBuff and Online players fixes

---

.jshintrc
calfSystem.css
calfSystem.js
fallenswordhelper.user.js

\# (major) FS: Inventory Manager
\# (major) FS: World Special Creatures Hide Create Group Buttons #7 
\# (major) FS: Disable deactivate prompts in profile (ajax debuff) #84 
\# (major) FS: New (Secure)Trade screens to fix composed pots #89 
\# (major) FS: Begin removal of old map code #88 
\# (major) FS: Min Lvl and Quick links on New Map #88 
\# (minor) FS: Make HCS menu remember collapsed section
\# (minor) FS: Fix quick send (items & gold) #87 
\# (minor) FS: AJAX Guild Mailbox
\# (minor) FS: Fix last_login over 30 days
\# (minor) FS: Improve highlighting Guild Log
\# (minor) FS: Allow use of back in Arena and UFSG
\# (minor) FS: Fix pick moves screen in Arena
\# (minor) FS: Fix groups table widths for HiDPI screens
\# (minor) FS: Preference to prevent moving composing buttons #91 
\# …

==Revision 1514 (PointyHair)==

---

calfSystem.js

Typo in GA
Cache inventory for Trade

Minor bug fix

---

src/modules/inventing/injectInvent.js

Just addresses issue #203 in case my other PR requires more review.

Updated Quick Invent for new API

---

README.md

(cherry picked from commit 0b2821c8e8ad7c85fe1fd4cac3e0812c50472407)

new badge and layout

---

src/modules/analytics/timing.js

(cherry picked from commit 74f9535269c905e9a212e786ab251a3d08e276c3)

start timers before GA is available

---

src/modules/ladder/optInWidget.js
src/modules/settings/otherPrefs.js
src/modules/settings/saveBoxes.json
src/modules/settings/simple.json
src/modules/support/dataObj.json

(cherry picked from commit 38674513a710471f58dbb03f437652da6935f1f1)

opt in pref

---

src/modules/notepad/whosGotWhat/whosGotWhat.js

(cherry picked from commit d1b61e0fa5da358451daa01e3c25833604540068)

whosgotwhat use rank fallback

---

src/modules/guild/guildXPLock.js

Reverts fallenswordhelper/fallenswordhelper#460

Revert "hide-guildxplock"

---

src/modules/chrome/helperMenu/HelperMenu.svelte
src/modules/chrome/helperMenu/functionLookup.js

Removed blank modal for gs export

---

src/modules/chrome/helperMenu/HelperMenu.svelte

the font has been bugging me, didn't know why!

helper-menu-style-tweaks

---

src/modules/chrome/helperMenu/functionLookup.js

find-buff-find-other

---

src/modules/_dataAccess/daBuffMarketDoAdd.js
src/modules/app/buffmarket/doAdd.js
src/modules/buffmarket/add/BigBuffPackages.svelte
src/modules/buffmarket/add/injectBigBuffPacakges.js
src/modules/chrome/pageSwitcher/pageSwitcher.js

Made modal to make multiple buff packages

---

src/modules/arena/completedArenas.js

Ajaxified completed arenas

---

src/modules/_dataAccess/daDeleteBuffPackage.js
src/modules/_dataAccess/daFeatureBuffPackage.js
src/modules/_dataAccess/daToggleBuffPackage.js
src/modules/app/buffmarket/deletePackage.js
src/modules/app/buffmarket/feature.js
src/modules/app/buffmarket/toggle.js
src/modules/buffmarket/injectManage.js
src/modules/buffmarket/manage.css
src/modules/chrome/pageSwitcher/pageSwitcher.js

Ajaxified buffmarket package managements buttons: toggle, delete, and feature.

Ajaxify manage buffmarket
